### ISSUE TITLE
Check for empty objects?

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdJson-schemas#127]
Should we disallow empty objects? This can be done using the [minProperties](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.14) flag.

**Comment by stansmith907** [comment]
I am checking all objects for .empty? before processing.  But handling empty objects does not always set an error condition.  

1. if I pass an object into a reader module and the object is empty I set a reader error.
2. if I am processing a JSON block which has an element that is an object to be passed to another module, I always test to see if the object is empty before passing (which likely negates test 1 if most all cases).  If the empty object is required I set a reader error, otherwise I just skip it.   

So empty objects are handled in the reader and not going to cause harm.  We can control empty objects some in the mdEditor, but we will need to support other generators of mdJson.  So I would not suggest having the validator set an error.  You could set a warning if you like.
