### ISSUE TITLE
metadataRepository 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#129]
'metadataRepository' is an array of requests for distribution of the resource metadata package.  This object is not part of the metadata record and will be handled by some server side function which is yet to be written.  In the future this server function could be added to mdTranslator to distribute the metadata record after translation.  

Definitions: 
* "repository" is a required element of type codelist "adiwg_repository".  Definition: "name or code for the metadata repository to which the metadata record is to be pushed".  For this to be automated the "repository" name will likely need to be an enum or controlled list.  I suggest we start with a controlled list but allow custom user input. 
* "metadataStandard" is an optional element of type codelist "adiwg_metadataStandard".  Definition: "indicates what documented standard the metadata record should be translated into before pushing to the repository.  

````json
{
  "metadataRepository": [
    {
      "repository": "",
      "metadataStandard": ""
    }
  ]
}
````

**Comment by jlblcc** [comment]
In thinking about this, I think we should limit the data properties to identification of the distributor. The other properties are not relevant to the mdJSON itself, rather would be actions performed by some API process _on_ the mdJSON record. We might include those properties as part of a mdEditor record (which wraps the mdJSON). I would suggest simplifying to something like this:

```{
  "metadataDistribution": [
    {
      "distributor": "contactId"
  ]
}```

Another, option is to use metadataInfo->alternateMetadataReference which is a citation. This might actually be the preferred option, since we can include it in ISO output. The original use case is the need to identify Data.gov as a distribution source for the metadata and alternateMetadataReference would actually suffice for this purpose.

We can create a codelist of distributors(with UUID-based contactIds) to be supported natively by the mdEditor, or a list of distributor contacts/citations as a NPM-based plug-in for use in the mdEditor.

**Comment by jlblcc** [comment]
Example above could be simplified to:

```json
{
  "metadataDistributor": [
     "contactId"
  ]
}
```

**Comment by stansmith907** [comment]
I did put the metadataDistribution block at the wrong level.  I should have, and will, move it up to mdJson (the top) and out of metadata{ }.  

I'm not completely comfortable placing the information in alternateMetadataReference.  To me that is a passive block reporting where other formats or previous versions of the metadata exist, but using it as a trigger for one or more metadata engines or clearinghouses to take some action is a stretch.  We can pull everything out but the clearinghouse if you like.  But eventually I think we will need to add format, pushMethod, and possibly ID back in if distribution goes beyond ScienceBase.

**Comment by stansmith907** [comment]
OK, I think we decided during our phone conversation that "pushMethod" and "metadataId" would be removed for now but may return as push services begin to be built.  We also renamed the block from "metadataDistribution" to "metadataRepository".  "metadataFormat" is no longer required allowing blank to substitute for a particular service to push using its metadata format default.

**Comment by jlblcc** [comment]
So, something like this?

````json
{
  "metadataRepository": [
    {
      "repositoryId": "",
      "metadataFormat": ""
    }
  ]
}
````

**Comment by stansmith907** [comment]
Yep, like that.  I think I made the change to the model then added a comment and only did the commit on the comment.  

This pass on the model update I added reference to two new codelists: "adiwg_repository" and "adiwg_metadataFormat".  Okay for me to add these to mdCodes?

**Comment by jlblcc** [comment]
Sure. If you do, use a UUID for the adiwg_repository codes.

**Comment by stansmith907** [comment]
Hum, I don't see the need for a UUID on the repository code.  I think the UUID belongs on the metadata record as associated with a repository, but we moved that element.  You want t put it back?  Or are you thinking something else?

**Comment by jlblcc** [comment]
I'm suggesting using a UUID instead of "001, 002, etc." In case we want to be able to definitively identify the repository via the codelist.

**Comment by stansmith907** [comment]
Okay, used UUIDs as codes and changed element name 'metadataFormat' to 'metadataStandard'
