### ISSUE TITLE
New Class - Instrument

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#215]
Class Definition: __instrument__
"designations for the measuring instruments"
See: ISO [MI_Instrument](https://schemas.isotc211.org/19115/-2/mac/2.2.0/mac/#element_MI_Instrument)

Rules:
 - [ ] optional
---
Element Definitions:
 * instrumentId: ( character ) "a unique mdJSON system identifier for the instrument" default: UUID
 * citation: [ citation ] "complete citation of the instrument"
 * identifier: { identifier } "unique identification of the instrument"
 * instrumentType: ( character ) "name of the type of instrument. Examples: framing, linescan,
push-broom, panframe"
 * description: ( character ) "textual description of the instrument"
 * mountedOn: ( platformId ) "platform on which the instrument is mounted"
 * history: [ MI_instrumentationEventList ] "list of events associated with the instrument"
 * hostId: { identifier } "identifier of the hosting instrument for a sensor"

Rules:
 - [ ] instrumentId: required
 - [ ] identifier: required
 - [ ] instrumentType: required

---
mdJson:
````json
{
   "acquisition": [
      {
         "instrument": [
            {
               "instrumentId": "instrument ID",
               "citation": [],
               "identifier": {},
               "instrumentType": "instrument type",
               "description": "instrument description",
               "mountedOn": "platformId",
               "history": "events list"
               "hostId": "host instrument ID"
            }
         ]
      }
   ]
}
````

**Comment by dwalt** [comment]
Added "hostId" and "history" elements.

**Comment by jwaspin** [comment]
@dwalt It looks like #250 and #251 are related to this and will also need to be completed as part of this, is that correct? It looks like `history` is an array of the event list objects? If that is correct, then there's a follow up question about the MI_InstrumentationEventTypeCode, which appears to be missing from http://standards.iso.org/iso/19115 although the list can still be found here https://wiki.esipfed.org/ISO_19115-3_Codelists#MI_InstrumentationEventTypeCode not only is that one of the esip links, the link to the code list is pointing to the wrong code list. What do we do about this one? Add it as an adiwg code list instead of iso so we can still use it? Keep it iso? Something else?

**Comment by dwalt** [comment]
@jwaspin Yes, InstrumentationEventList is an array of events associated with an Instrument. Event is like a lookup table of Event types that have a pre-defined relevance to the Instrument. From the perspective of the Instrument it is the "History" of events. This can be calibrations, operational status, milestones, etc. One would think there would be a defined temporal or process ordering, but there is not. Order is purely sequential. We could utilize CitationDate to identify temporal ordering in the UI and the write to mdJSON. I have emailed you the correct EventTypeCode list.

**Comment by jwaspin** [comment]
#254

**Comment by hmaier-fws** [comment]
Updated definition of instrumentId to:
instrumentId: ( character ) "a unique mdJSON system identifier for the instrument" default: UUID
